// questions.js
window.TEST_QUESTIONS = {
  topic1: [
    {
      q: "Talaba hujayraning fundamental negiz sifatida organizm tuzilishi va funksiyasini belgilashini o‘rganmoqda. Bu ta’rif qaysi fan doirasiga to‘g‘ri keladi?",
      a: [
        "Hujayra biologiyasi",
        "Molekulyar genetika",
        "Gistologiya",
        "Embriologiya",
        "Biokimyo",
      ],
      correct: 0,
    },
    {
      q: "Hujayra biologiyasi fanining ikki asosiy bo‘limga ajratilishi ilmiy jihatdan nimani ta’minlaydi?",
      a: [
        "Tuzilish va irsiyat ajratilishi",
        "To‘qima va organ farqlanishi",
        "Modda almashinuvi tahlili",
        "Energiya balansini aniqlash",
        "Populyatsiya o‘sishini baholash",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi jarayonlardan qaysi biri hujayra bo‘limiga kirmaydi?",
      a: [
        "Hujayra metabolizmi",
        "Hujayra sikli",
        "Gen ifodalanishi",
        "Hujayra organellalari",
        "Hujayralararo aloqa",
      ],
      correct: 2,
    },
    {
      q: "Genetika bo‘limining asosiy o‘rganish obyekti noto‘g‘ri ko‘rsatilgan javobni aniqlang.",
      a: [
        "Genetik nasldorlik",
        "Irsiy belgilar",
        "Xromosoma tuzilishi",
        "Hujayra metabolizmi",
        "DNK ifodalanishi",
      ],
      correct: 3,
    },
    {
      q: "Hayotning tuzilish darajalarida organoidlardan keyingi daraja qaysi hisoblanadi?",
      a: ["Hujayra", "To‘qima", "Organ", "Molekula", "Organizm"],
      correct: 0,
    },
    {
      q: "Hujayraning kimyoviy tarkibiga kiruvchi anorganik modda noto‘g‘ri ko‘rsatilgan javobni toping.",
      a: ["Suv", "Makroelement", "Mikroelement", "Oqsil", "Ionlar"],
      correct: 3,
    },
    {
      q: "Quyidagi uglevodlardan qaysi biri polisaxarid hisoblanmaydi?",
      a: ["Kraxmal", "Selluloza", "Glikogen", "Xitin", "Laktoza"],
      correct: 4,
    },
    {
      q: "Oqsil molekulasida faqat peptid bog‘lar qatnashadigan strukturaviy daraja qaysi?",
      a: [
        "Birlamchi",
        "Ikkilamchi",
        "Uchlamchi",
        "To‘rtlamchi",
        "Denaturatsiyalangan",
      ],
      correct: 0,
    },
    {
      q: "Disulfid (S–S) bog‘lari qaysi oqsil strukturasi uchun xos?",
      a: [
        "Birlamchi",
        "Ikkilamchi",
        "Uchlamchi",
        "To‘rtlamchi",
        "Fragmentlangan",
      ],
      correct: 2,
    },
    {
      q: "pH pasayishi va harorat oshishi oqibatida oqsil funksiyasining yo‘qolishi qanday jarayon?",
      a: [
        "Denaturatsiya",
        "Renaturatsiya",
        "Glikozillanish",
        "Polimerizatsiya",
        "Oksidlanish",
      ],
      correct: 0,
    },
    {
      q: "Shaperon oqsillari ishtirokida oqsilning qayta tiklanishi nima deb ataladi?",
      a: [
        "Renaturatsiya",
        "Denaturatsiya",
        "Translyatsiya",
        "Replikatsiya",
        "Izomerizatsiya",
      ],
      correct: 0,
    },
    {
      q: "Glikoprotein va peptidoglikan orasidagi asosiy farq nimada?",
      a: [
        "Uglevod miqdorida",
        "Oqsil tarkibida",
        "Bog‘lanish turida",
        "Zaryad xususiyatida",
        "Joylashish hududida",
      ],
      correct: 0,
    },
    {
      q: "O-bog‘langan glikozillanish qaysi aminokislotalarda uchraydi?",
      a: [
        "Serin va treonin",
        "Asparagin va glitsin",
        "Alanin va valin",
        "Lizin va arginin",
        "Fenilalanin va tirozin",
      ],
      correct: 0,
    },
    {
      q: "Sial kislotalarning hujayra yuzasidagi asosiy vazifasi nimadan iborat?",
      a: [
        "Manfiy zaryad berish",
        "Energiya ishlab chiqarish",
        "Oqsil sintezini tezlatish",
        "DNKni himoyalash",
        "Ion almashinuvini oshirish",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi moddalar ichidan glikozaminoglikanlarga mansubini aniqlang.",
      a: ["Gialuron kislota", "Glikogen", "Saxaroza", "Laktoza", "Xitin"],
      correct: 0,
    },
    {
      q: "Lipidlarning suvda erimasligining asosiy sababi nima?",
      a: [
        "Gidrofob xususiyati",
        "Ionlanish darajasi",
        "Molekula kattaligi",
        "Zanjir uzunligi",
        "Bog‘lanish soni",
      ],
      correct: 0,
    },
    {
      q: "Lipoprotein tarkibidagi oqsil qismi qanday nomlanadi?",
      a: ["Apoprotein", "Glikoprotein", "Proteoglikan", "Ferment", "Shaperon"],
      correct: 0,
    },
    {
      q: "Aterosklerozda eng xavfli hisoblangan lipoprotein qaysi?",
      a: ["LDL", "HDL", "VLDL", "IDL", "Xilomikron"],
      correct: 0,
    },
    {
      q: "DNK va RNK o‘rtasidagi asosiy kimyoviy farq nimada?",
      a: [
        "Uglevod va azot asosida",
        "Fosfat qoldig‘ida",
        "Zanjir uzunligida",
        "Bog‘lanish turida",
        "Zaryad miqdorida",
      ],
      correct: 0,
    },
    {
      q: "Xromosoma tarkibidagi DNK qaysi oqsillar bilan bog‘langan?",
      a: [
        "Giston oqsillari",
        "Ferment oqsillari",
        "Struktur oqsillar",
        "Transport oqsillari",
        "Membrana oqsillari",
      ],
      correct: 0,
    },
  ],
  topic2: [
    {
      q: "Hujayra ichini tashqi muhitdan ajratib turuvchi asosiy tuzilma qaysi?",
      a: [
        "Hujayra membranasi",
        "Yadro qobig‘i",
        "Mitoxondriya",
        "Sitoplazma",
        "Endoplazmatik to‘r",
      ],
      correct: 0,
    },
    {
      q: "Plazmolemma orqali hujayra uchun zarur moddalarning kirib-chiqishi qaysi funksiyaga kiradi?",
      a: [
        "Transport funksiyasi",
        "Energetik funksiyasi",
        "Genetik boshqaruv",
        "Oqsil sintezi",
        "Signal almashinuvi",
      ],
      correct: 0,
    },

    {
      q: "Plazmolemmaning o‘rtacha qalinligi qancha?",
      a: ["7.5 nm", "15 nm", "3 nm", "25 nm", "5.5 nm"],
      correct: 0,
    },
    {
      q: "Hujayra membranasida uchramaydigan modda qaysi?",
      a: [
        "Nuklein kislotalar",
        "Fosfolipidlar",
        "Glikoproteinlar",
        "Karbogidratlar",
        "Xolesterol",
      ],
      correct: 0,
    },
    {
      q: "Lipid qo‘shqavat qaysi moddalarga oson o‘tkazuvchan?",
      a: [
        "Qutbsiz va yog‘da eruvchan",
        "Zaryadlangan ionlar",
        "Periferik va integral",
        "Oqsil va uglevodlar",
        "Aminokislotalar",
      ],
      correct: 0,
    },
    {
      q: "Ionlarning membranadan o‘ta olmasligining sababi nima?",
      a: [
        "Gidrofob yadro",
        "Proteinlar kamligi",
        "Membrana yupqaligi",
        "Karbogidrat qatlami",
        "Asimmetriklik funksiya",
      ],
      correct: 0,
    },
    {
      q: "Fosfolipidlarning amfipatikligi nimani anglatadi?",
      a: [
        "Gidrofil va gidrofob",
        "Faqat suvda eriydi",
        "Faqat yog‘da eriydi",
        "Zaryadli va zaryadsiz",
        "Qutbli va qutbsiz",
      ],
      correct: 0,
    },
    {
      q: "Hujayra membranasida eng ko‘p uchraydigan lipid turi qaysi?",
      a: [
        "Fosfolipidlar",
        "Glikolipidlar",
        "Steroidlar",
        "Triglitseridlar",
        "Mumlar",
      ],
      correct: 0,
    },
    {
      q: "Fosfatidilxolin asosan qaysi qavatda joylashadi?",
      a: [
        "Tashqi qavatda",
        "Ichki qavatda",
        "Har ikkala qavatda",
        "Yadro membranasida",
        "Mitoxondriyada",
      ],
      correct: 0,
    },
    {
      q: "Ichki qavat uchun xos fosfolipidlar qaysilar?",
      a: [
        "Fosfatidilserin va fosfatidilinozitol",
        "Fosfatidilxolin va sfingomiyelin",
        "Xolesterol",
        "Glikolipidlar",
        "Triglitseridlar",
      ],
      correct: 0,
    },
    {
      q: "Membrananing mozaik modeli nimani tushuntiradi?",
      a: [
        "Oqsillarning lipidlar orasida harakatlanishini",
        "Membrananing qattiqligini",
        "Uglevodlar iceberg kabi suzib yurishini",
        "Ionlarning erkin o‘tishini",
        "Statik tuzilmani",
      ],
      correct: 0,
    },
    {
      q: "Periferik membrana oqsillarining xususiyati qaysi?",
      a: [
        "Lipid qo‘shqavatni kesib o‘tmaydi",
        "Transmembranal domeni bor",
        "Faqat tashqi tomonda bo‘ladi",
        "Lipid qo'shqavatni kesib o'tadi",
        "Gidrofob yadroni egallaydi",
      ],
      correct: 0,
    },
    {
      q: "Integral membrana oqsillarining asosiy vazifasi qaysi?",
      a: [
        "Retseptor va adgeziya",
        "DNK replikatsiyasi",
        "ATP sintezi",
        "Oqsil parchalanishi",
        "Signal transduksiyasi, uglevod parchalanishi",
      ],
      correct: 0,
    },
    {
      q: "GPI orqali birikkan oqsillar qaysi turga kiradi?",
      a: ["Periferik", "Integral", "Yadro", "Sitoskelet", "Sekretor"],
      correct: 0,
    },
    {
      q: "Hujayraning immun tizim tomonidan tanilishi nimaga bog‘liq?",
      a: [
        "Integral membrana oqsillariga",
        "Lipid dumlariga",
        "Xolesterolga",
        "Fosfolipid boshlariga",
        "Periferik membrana oqsillariga",
      ],
      correct: 0,
    },
    {
      q: "Fosfatidilxolinning yo‘g‘on ichakdagi vazifasi nima?",
      a: [
        "Patogenlarga qarshi gidrofob to‘siq",
        "Energiya ishlab chiqarish",
        "Ion nasosi vazifasi",
        "Gormon sintezi",
        "Fosfatifilxolinni normal ishlashini ta'minlash",
      ],
      correct: 0,
    },
  ],

  topic3: [
    {
      q: "Membrana orqali moddalarning qat’iy nazoratda o‘tishi hujayrada nimani ta’minlaydi?",
      a: [
        "Ichki muhit barqarorligi",
        "Energiya ishlab chiqarish",
        "Genetik axborot uzatish",
        "Bo‘linish tezlashuvi",
        "Oqsil sintezi faolligi",
      ],
      correct: 0,
    },
    {
      q: "Selektiv o‘tkazuvchanlik mohiyati nimada ifodalanadi?",
      a: [
        "Tanlab o‘tkazish xususiyati",
        "Ionlarning erkin o‘tishi",
        "Faqat suv o‘tishi",
        "Yirik molekula o‘tishi",
        "Energiya talab qilinishi",
      ],
      correct: 0,
    },
    {
      q: "Energiya sarfisiz, gradient bo‘yicha kechuvchi transport turi qaysi?",
      a: [
        "Passiv transport turi",
        "Birlamchi aktiv turi",
        "Ikkilamchi aktiv turi",
        "Vezikular transport turi",
        "Transsitoz mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "Oddiy diffuziyada modda harakati nimaga bog‘liq?",
      a: [
        "Konsentratsiya gradientiga",
        "ATF parchalanishiga",
        "Oqsil faolligiga",
        "Vezikula hosiliga",
        "Membrana qalinligiga",
      ],
      correct: 0,
    },
    {
      q: "Qaysi moddalarning o‘tishi oddiy diffuziya bilan kechadi?",
      a: [
        "Kichik qutbsiz molekulalar",
        "Zaryadlangan ionlar guruhi",
        "Yirik organik molekulalar",
        "Oqsil strukturalari",
        "Nuklein kislotalar",
      ],
      correct: 0,
    },
    {
      q: "Yengillashgan diffuziyaning asosiy belgisi qaysi?",
      a: [
        "Oqsil ishtiroki bilan",
        "ATF sarfi bilan",
        "Gradientga qarshi",
        "Vezikula orqali",
        "Suv bilan bog‘liq",
      ],
      correct: 0,
    },
    {
      q: "Sistinuriya kasalligi qaysi buzilish bilan bog‘liq?",
      a: [
        "Tashuvchi oqsil nuqsoni",
        "Oddiy diffuziya yetishmovchiligi",
        "Osmos kuchayishi holati",
        "Ekzotsitoz buzilishi",
        "Fagotsitoz pasayishi",
      ],
      correct: 0,
    },
    {
      q: "Gradientga qarshi va energiya bilan kechuvchi transport qaysi?",
      a: [
        "Aktiv transport turi",
        "Oddiy diffuziya turi",
        "Yengillashgan diffuziya",
        "Pinotsitoz jarayoni",
        "Osmos mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "Birlamchi aktiv transport energiyani qayerdan oladi?",
      a: [
        "ATF parchalanishidan",
        "Ion gradientidan",
        "Membrana potensialidan",
        "Glikogen parchalanishidan",
        "NADH oksidlanishidan",
      ],
      correct: 0,
    },
    {
      q: "Ikkilamchi aktiv transport energiya manbai nima?",
      a: [
        "Elektrokimyoviy gradient",
        "Bevosita ATF",
        "Oqsil denaturatsiyasi",
        "Vezikula parchalanishi",
        "Osmotik bosim",
      ],
      correct: 0,
    },
    {
      q: "SGLT2 tashuvchisi qaysi mexanizm asosida ishlaydi?",
      a: [
        "Ikkilamchi aktiv transport",
        "Birlamchi aktiv transport",
        "Oddiy diffuziya",
        "Yengillashgan diffuziya",
        "Transsitoz mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "SGLT2 bloklanganda asosiy klinik natija nima?",
      a: [
        "Glyukozuriya kuchayishi",
        "Hujayraga glyukoza kirishi",
        "ATF ishlab chiqarilishi",
        "Osmos to‘xtashi",
        "Natriy yo‘qolishi",
      ],
      correct: 0,
    },
    {
      q: "Yirik molekulalarning vezikula orqali o‘tishi qanday ataladi?",
      a: [
        "Vezikular transport",
        "Passiv transport",
        "Oddiy diffuziya",
        "Osmos jarayoni",
        "Yengillashgan diffuziya",
      ],
      correct: 0,
    },
    {
      q: "Hujayradan tashqariga modda chiqarilishi nima deyiladi?",
      a: [
        "Ekzotsitoz jarayoni",
        "Endotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Transsitoz jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Qattiq zarrachalar yutilishi qaysi mexanizm bilan kechadi?",
      a: [
        "Fagotsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Ekzotsitoz jarayoni",
        "Oddiy diffuziya",
        "Osmos jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Suyuqlikning vezikula orqali yutilishi nima deyiladi?",
      a: [
        "Pinotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Ekzotsitoz jarayoni",
        "Transsitoz jarayoni",
        "Aktiv transport",
      ],
      correct: 0,
    },
    {
      q: "Endotsitoz va ekzotsitoz birga kechsa nima deyiladi?",
      a: [
        "Transsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Oddiy diffuziya",
        "Osmos jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Suvning yarimo‘tkazuvchan membrana orqali o‘tishi nima?",
      a: [
        "Osmos jarayoni",
        "Diffuziya jarayoni",
        "Aktiv transport",
        "Ekzotsitoz jarayoni",
        "Filtratsiya jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Hujayra ichki suyuqligiga teng eritma qanday ataladi?",
      a: [
        "Izotonik eritma",
        "Gipertonik eritma",
        "Gipotonik eritma",
        "Giperaktiv eritma",
        "Passiv eritma",
      ],
      correct: 0,
    },
    {
      q: "Hujayra gipotonik muhitda qanday o‘zgaradi?",
      a: [
        "Suv kirib shishadi",
        "Suv chiqib kichrayadi",
        "Transport to‘xtaydi",
        "ATF ortib ketadi",
        "Membrana buziladi",
      ],
      correct: 0,
    },
  ],

  topic4: [
    {
      q: "Organella nima?",
      a: ["Tuzilma", "Hujayra", "Molekula", "Ferment"],
      correct: 0,
    },
    {
      q: "Organellalar hujayrada nimani ta’minlaydi?",
      a: ["Gomeostaz", "Mitroz", "Replikatsiya", "Diffuziya"],
      correct: 0,
    },
    {
      q: "Membranasiz organellaga qaysi kiradi?",
      a: ["Ribosoma", "Lizosoma", "Mitoxondriya", "Yadro"],
      correct: 0,
    },
    {
      q: "Bir membranali organellani belgilang",
      a: ["Lizosoma", "Yadro", "Ribosoma", "Sitoskelet"],
      correct: 0,
    },
    {
      q: "Ikki membranali organella qaysi?",
      a: ["Mitoxondriya", "Golji", "Lizosoma", "Ribosoma"],
      correct: 0,
    },
    {
      q: "Genetik material saqlovchi organella",
      a: ["Yadro", "Golji", "Lizosoma", "Peroksisoma"],
      correct: 0,
    },
    {
      q: "Endoplazmatik to‘r vazifasi",
      a: ["Transport", "Harakat", "Bo‘linish", "Himoya"],
      correct: 0,
    },
    {
      q: "DET nimani sintez qiladi?",
      a: ["Oqsil", "Lipid", "ATP", "DNK"],
      correct: 0,
    },
    {
      q: "SET asosiy vazifasi",
      a: ["Detoksikatsiya", "Translyatsiya", "Replikatsiya", "Transkripsiya"],
      correct: 0,
    },
    {
      q: "SETda qaysi ion saqlanadi?",
      a: ["Kalsiy", "Natriy", "Kaliy", "Xlor"],
      correct: 0,
    },
    {
      q: "Golji apparati vazifasi",
      a: ["Saralash", "Replikatsiya", "Translyatsiya", "Energiya"],
      correct: 0,
    },
    {
      q: "Golji apparatining kirish tomoni",
      a: ["Sis", "Trans", "Medial", "Lateral"],
      correct: 0,
    },
    {
      q: "Golji apparatidan vezikulalar qayerga ketadi?",
      a: ["Lizosoma", "Yadro", "Ribosoma", "Sitoskelet"],
      correct: 0,
    },
    {
      q: "Hujayra energiya manbai",
      a: ["Mitoxondriya", "Lizosoma", "Golji", "Ribosoma"],
      correct: 0,
    },
    {
      q: "Mitoxondriya nechta membranali?",
      a: ["Ikki", "Bir", "Uch", "Nol"],
      correct: 0,
    },
    {
      q: "Mitoxondrial DNK qanday shaklda?",
      a: ["Halqa", "Chiziq", "Spiral", "Tarmoqli"],
      correct: 0,
    },
    {
      q: "Mitoxondriya qaysi hujayrada yo‘q?",
      a: ["Eritrotsit", "Muskul", "Neyron", "Gepatotsit"],
      correct: 0,
    },
    {
      q: "Lizosoma vazifasi",
      a: ["Parchalash", "Sintez", "Saqlash", "Transport"],
      correct: 0,
    },
    {
      q: "Lizosoma fermentlari muhiti",
      a: ["Kislotali", "Neytral", "Ishqoriy", "O‘zgaruvchan"],
      correct: 0,
    },
    {
      q: "Peroksisoma qanday membranali?",
      a: ["Bir", "Ikki", "Uch", "Membranasiz"],
      correct: 0,
    },
    {
      q: "Peroksisomada parchalanadigan modda",
      a: ["H2O2", "CO2", "O2", "H2O"],
      correct: 0,
    },
    {
      q: "Proteasoma vazifasi",
      a: ["Oqsil", "Lipid", "Uglevod", "DNK"],
      correct: 0,
    },
    {
      q: "Sitoskelet vazifasi",
      a: ["Tayanch", "Sintez", "Hazm", "Sekretsiya"],
      correct: 0,
    },
    {
      q: "Mikrofilament tarkibi",
      a: ["Aktin", "Tubulin", "Keratin", "Kollagen"],
      correct: 0,
    },
    {
      q: "Mikronaycha oqsili",
      a: ["Tubulin", "Aktin", "Keratin", "Miozin"],
      correct: 0,
    },
  ],
  topic5: [
    {
      q: "Yadro nima?",
      a: [
        "DNK saqlovchi ikki qavatli membranali organella",
        "Oqsil sintez qiluvchi tuzilma",
        "Energiya ishlab chiqaruvchi organella",
        "Sitoplazma qismi",
      ],
      correct: 0,
    },
    {
      q: "Yadro qaysi hujayralarda uchraydi?",
      a: [
        "Faqat eukariot hujayralarda",
        "Faqat prokariot hujayralarda",
        "Barcha hujayralarda",
        "Faqat nerv hujayralarida",
      ],
      correct: 0,
    },
    {
      q: "Yadro nega hujayraning “miyasi” deb ataladi?",
      a: [
        "Hujayra hayotiy jarayonlarini boshqaradi",
        "ATP ishlab chiqaradi",
        "Moddalarni parchalaydi",
        "Harakatni ta’minlaydi",
      ],
      correct: 0,
    },
    {
      q: "Yadroda saqlanadigan genetik material nima?",
      a: ["DNK", "RNK", "Oqsil", "Lipid"],
      correct: 0,
    },
    {
      q: "DNKdagi axborot yadrodan tashqariga qanday chiqadi?",
      a: ["RNK orqali", "Oqsil orqali", "Ferment orqali", "Lipid orqali"],
      correct: 0,
    },
    {
      q: "RNK yadroni tark etgach, qayerda oqsil sintezida ishtirok etadi?",
      a: [
        "Ribosomalar bilan",
        "Mitoxondriyada",
        "Goldji apparatida",
        "Lizosomada",
      ],
      correct: 0,
    },
    {
      q: "Yadro qobig‘i qanday tuzilishga ega?",
      a: [
        "Ichki va tashqi membranadan iborat",
        "Bitta membranali",
        "Membranasiz",
        "Faqat oqsillardan tashkil topgan",
      ],
      correct: 0,
    },
    {
      q: "Yadro qobig‘i orasidagi bo‘shliq qaysi tuzilma bilan bog‘langan?",
      a: [
        "Donador endoplazmatik to‘r",
        "Silliq endoplazmatik to‘r",
        "Mitoxondriya",
        "Lizosoma",
      ],
      correct: 0,
    },
    {
      q: "Yadro teshikchalari (poralari) vazifasi nima?",
      a: [
        "Moddalarning yadroga kirib-chiqishini boshqarish",
        "DNK sintez qilish",
        "Ribosoma ishlab chiqarish",
        "Energiya saqlash",
      ],
      correct: 0,
    },
    {
      q: "Xromatin nima?",
      a: [
        "Oqsillar atrofida o‘ralgan DNK",
        "Kuchli spirallashgan xromosoma",
        "Faqat DNK",
        "Faqat oqsil",
      ],
      correct: 0,
    },
    {
      q: "Xromatin va yadrocha qaysi muhitda joylashgan?",
      a: ["Nukleoplazmada", "Sitoplazmada", "Stromada", "Matriksda"],
      correct: 0,
    },
    {
      q: "DNK tarkibiga qaysi nukleotidlar kiradi?",
      a: ["A, T, S, G", "A, U, S, G", "A, T, U, G", "A, S, G, U"],
      correct: 0,
    },
    {
      q: "Yadrodagi barcha genlar majmuasi nima deb ataladi?",
      a: ["Genom", "Xromosoma", "Proteom", "Fenotip"],
      correct: 0,
    },
    {
      q: "Giston oqsillari DNK bilan nega bog‘lanadi?",
      a: [
        "Musbat zaryadlanganligi sababli",
        "Manfiy zaryadlanganligi sababli",
        "Neytral bo‘lgani uchun",
        "Lipid tabiatli bo‘lgani uchun",
      ],
      correct: 0,
    },
    {
      q: "Odam somatik hujayralarida nechta xromosoma mavjud?",
      a: ["46", "23", "44", "48"],
      correct: 0,
    },
  ],
  topic6: [
    {
      q: "Hujayralararo signal transduksiyasi nimani ta’minlaydi?",
      a: [
        "Hujayralar muvofiqlashgan faoliyati",
        "Hujayralar mustaqil yashashi",
        "Faqat genetik axborot almashuvi",
        "Faqat energetik jarayonlar kechishi",
      ],
      correct: 0,
    },
    {
      q: "Kimyoviy signal molekulalari qanday ataladi?",
      a: [
        "Ligand deb nomlanadi",
        "Ferment deb nomlanadi",
        "Substrat deb nomlanadi",
        "Koferment deb nomlanadi",
      ],
      correct: 0,
    },
    {
      q: "Ligand signal uzatishi uchun nima zarur?",
      a: [
        "Mos nishon tuzilma",
        "Yetarli energiya manbai",
        "Maxsus ferment ishtiroki",
        "To‘g‘ridan to‘g‘ri kontakt",
      ],
      correct: 0,
    },
    {
      q: "Quyidagilardan qaysi nishon tuzilma hisoblanadi?",
      a: [
        "Membranaviy retseptor oqsili",
        "Sitoplazmatik ribosoma zarrachasi",
        "Yadro qobig‘i membranasi",
        "Mitoxondriya ichki membranasi",
      ],
      correct: 0,
    },
    {
      q: "Autokrin signalning asosiy xususiyati nima?",
      a: [
        "Hujayraning o‘ziga ta’siri",
        "Qo‘shni hujayraga ta’siri",
        "Uzoq masofaga ta’siri",
        "Faqat gormonlar ishtiroki",
      ],
      correct: 0,
    },
    {
      q: "Parakrin signal qanday masofada ta’sir ko‘rsatadi?",
      a: [
        "Qisqa masofada lokal",
        "Uzoq masofada tizimli",
        "Faqat qon orqali",
        "Faqat nerv tolalari",
      ],
      correct: 0,
    },
    {
      q: "Yallig‘lanishda makrofaglar qaysi ligandlarni chiqaradi?",
      a: [
        "IL-1 IL-6 TNF-α",
        "Insulin glukagon somatostatin",
        "Adrenalin noradrenalin dopamin",
        "Tiroksin triyodtironin kalsitonin",
      ],
      correct: 0,
    },
    {
      q: "AAG oqsili qaysi jarayonda oshadi?",
      a: [
        "Yallig‘lanish o‘tkir fazasi",
        "Energiya almashinuvi jarayoni",
        "Nerv impulsi uzatilishi",
        "Mushak qisqarishi jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Endokrin signal qanday yo‘l bilan uzatiladi?",
      a: [
        "Qon aylanish tizimi",
        "Hujayralararo bevosita aloqa",
        "Sinaptik nerv bo‘shlig‘i",
        "Mahalliy to‘qima suyuqligi",
      ],
      correct: 0,
    },
    {
      q: "Endokrin ligandlar qanday nomlanadi?",
      a: [
        "Gormonlar deb ataladi",
        "Mediatorlar deb ataladi",
        "Fermentlar deb ataladi",
        "Retseptorlar deb ataladi",
      ],
      correct: 0,
    },
    {
      q: "Ikkilamchi messenjerning vazifasi nima?",
      a: [
        "Signalni ichkariga uzatish",
        "DNKni replikatsiya qilish",
        "Oqsilni parchalanishini ta’minlash",
        "Membranani mexanik mustahkamlash",
      ],
      correct: 0,
    },
    {
      q: "Quyidagilardan qaysi endokrin bez hisoblanadi?",
      a: [
        "Qalqonsimon bez tuzilmasi",
        "O‘pka alveola epiteliyasi",
        "Jigar parenxima hujayralari",
        "Teri epidermis qatlami",
      ],
      correct: 0,
    },
  ],
  topic7: [
    {
      q: "Retseptorlar qanday biologik tuzilma hisoblanadi?",
      a: [
        "Signallarni qabul qiluvchi oqsil tuzilmalari",
        "Energiya ishlab chiqaruvchi organoidlar",
        "Genetik axborot saqlovchi tuzilmalar",
        "Moddalar almashinuvi olib boruvchilar",
      ],
      correct: 0,
    },
    {
      q: "Ligand retseptorga birikkach qanday javoblar yuzaga kelishi mumkin?",
      a: [
        "Biologik effekt hosil bo‘lishi yoki uzatilishi",
        "Faqat issiqlik energiyasi ajralishi",
        "Hujayra bo‘linishi to‘xtab qolishi",
        "DNK replikatsiyasi tezlashishi",
      ],
      correct: 0,
    },
    {
      q: "Retseptorlar signalni asosan nima orqali uzatadi?",
      a: [
        "Ikkilamchi messenjerlar orqali",
        "To‘g‘ridan to‘g‘ri DNK orqali",
        "Faqat membrana diffuziyasi bilan",
        "ATP parchalanishi hisobiga",
      ],
      correct: 0,
    },
    {
      q: "Quyidagilardan qaysi ikkilamchi messenjer hisoblanadi?",
      a: [
        "sAMF va sGMF molekulalari",
        "DNK va RNK molekulalari",
        "Ferment va substrat komplekslari",
        "Oqsil va lipid birikmalari",
      ],
      correct: 0,
    },
    {
      q: "Retseptorlar joylashuviga ko‘ra qanday sinflanadi?",
      a: [
        "Ekstrasellular va intrasellular turlarga",
        "Faol va nofaol holatlarga",
        "Katta va kichik molekulalarga",
        "Doimiy va vaqtinchalik shakllarga",
      ],
      correct: 0,
    },
    {
      q: "Ionotrop retseptorlarning asosiy vazifasi nima?",
      a: [
        "Ionlarning membrana orqali o‘tishini ta’minlash",
        "Gen ekspressiyasini boshqarish",
        "Oqsil sintezini to‘xtatish",
        "Energiya zahirasini saqlash",
      ],
      correct: 0,
    },
    {
      q: "Ionotrop retseptorlar ko‘proq qayerda uchraydi?",
      a: [
        "Neyronal sinapslar sohasida",
        "Jigar parenxima hujayralarida",
        "Buyrak filtratsiya tizimida",
        "Suyak to‘qimalari orasida",
      ],
      correct: 0,
    },
    {
      q: "Metabotrop retseptorlar qanday xususiyatga ega?",
      a: [
        "G proteinlar bilan ishlovchi tuzilmalar",
        "Ion kanallarni bevosita ochuvchilar",
        "Faqat yadroda joylashuvchilar",
        "Ferment bo‘lmagan oqsillar",
      ],
      correct: 0,
    },
    {
      q: "Metabotrop retseptorlar membranani necha marta kesib o‘tadi?",
      a: [
        "Yetti marotaba kesib o‘tadi",
        "Besh marotaba kesib o‘tadi",
        "Uch marotaba kesib o‘tadi",
        "Bir marotaba kesib o‘tadi",
      ],
      correct: 0,
    },
    {
      q: "G protein tarkibiga qaysi subbirliklar kiradi?",
      a: [
        "Alfa beta va gamma subbirliklar",
        "Faqat alfa subbirlik mavjud",
        "Ikki xil beta subbirlik",
        "Bitta gamma subbirlik",
      ],
      correct: 0,
    },
    {
      q: "GαS subbirlik faollashganda qaysi ferment ishga tushadi?",
      a: [
        "Adenilat siklaza fermenti",
        "Fosfolipaza A fermenti",
        "DNK polimeraza fermenti",
        "RNK ligaza fermenti",
      ],
      correct: 0,
    },
    {
      q: "GαI subbirlikning asosiy ta’siri nimadan iborat?",
      a: [
        "sAMF miqdorini kamaytirish",
        "Kalsiy ionlarini ko‘paytirish",
        "DNK transkripsiyasini kuchaytirish",
        "Membrana depolyarizatsiyasini chaqirish",
      ],
      correct: 0,
    },
    {
      q: "Fosfatidilinozitol mexanizmida qaysi moddalar hosil bo‘ladi?",
      a: [
        "IP3 va DAG ikkilamchi messenjerlari",
        "sAMF va sGMF molekulalari",
        "ATF va GTF nukleotidlari",
        "Natriy va kaliy ionlari",
      ],
      correct: 0,
    },
    {
      q: "IP3 ning asosiy vazifasi nimadan iborat?",
      a: [
        "Endoplazmatik to‘rdan Ca2+ chiqarish",
        "Protein kinaza C faollashtirish",
        "Adenilat siklazani bloklash",
        "DNK sintezini boshlash",
      ],
      correct: 0,
    },
    {
      q: "DAG qaysi fermentni faollashtiradi?",
      a: [
        "Protein kinaza C fermentini",
        "Protein kinaza A fermentini",
        "Adenilat siklaza fermentini",
        "DNK giraza fermentini",
      ],
      correct: 0,
    },
    {
      q: "Enzimatik retseptorlarning eng muhim turi qaysi?",
      a: [
        "Tirozinkinaza bilan ishlovchi retseptorlar",
        "Ion kanalli retseptorlar",
        "Yadro membranali retseptorlar",
        "Sitoplazmatik strukturaviy oqsillar",
      ],
      correct: 0,
    },
    {
      q: "Enzimatik retseptorlarda ligand qayerga birikadi?",
      a: [
        "Retseptorning tashqi domeniga",
        "Retseptorning yadro qismiga",
        "Sitoplazmatik ferment markaziga",
        "DNK bilan bog‘lovchi qismga",
      ],
      correct: 0,
    },
    {
      q: "Intrasellular retseptorlar qayerda joylashadi?",
      a: [
        "Sitoplazma va yadro ichida",
        "Faqat hujayra membranasida",
        "Mitoxondriya ichki qismida",
        "Endoplazmatik to‘r bo‘shlig‘ida",
      ],
      correct: 0,
    },
    {
      q: "Intrasellular retseptorlar bilan qaysi moddalar ishlaydi?",
      a: [
        "Steroid va tireoid gormonlar bilan",
        "Faqat peptid gormonlar bilan",
        "Faqat neyromediatorlar bilan",
        "Faqat ion kanallari orqali",
      ],
      correct: 0,
    },
    {
      q: "Yadro retseptorlarining asosiy vazifasi nima?",
      a: [
        "Gen ekspressiyasi va transkripsiyani boshqarish",
        "Ion oqimini tezlashtirish",
        "Membrana potentsialini o‘zgartirish",
        "Ferment parchalanishini kuchaytirish",
      ],
      correct: 0,
    },
  ],

  topic5_6: [
    {
      q: "Hujayra yadrosining asosiy vazifasi nima?",
      a: [
        "Genetik materialni saqlash va hujayra faoliyatini boshqarish",
        "Protein sintezini boshlash",
        "Lipid sintezini ta’minlash",
        "Kalsiy zaxira qilish",
        "Sitoskeletni mustahkamlash",
      ],
      correct: 0,
    },
    {
      q: "Yadro qobig‘i qanday membranalardan tashkil topgan?",
      a: [
        "Tashqi va ichki ikki qavatli fosfolipid membranalari",
        "Faqat bitta lipid qavati",
        "Ribosoma bilan qoplangan membrana",
        "SET va DET membranalari",
        "Golji apparati membranasi",
      ],
      correct: 0,
    },
    {
      q: "Yadro teshikchalari (nuclear pores) vazifasi nima?",
      a: [
        "Moddalarning yadroga kirib-chiqishini tartibga solish",
        "Protein sintezini boshlash",
        "Lipid sintezini oshirish",
        "Xromosomalarni himoya qilish",
        "Mikronaycha hosil qilish",
      ],
      correct: 0,
    },
    {
      q: "Xromatin va xromosoma farqi nima?",
      a: [
        "Xromatin - bo‘linish paytida spirallashmagan, xromosoma - bo‘linishdan oldin spirallashgan DNK",
        "Xromatin faqat proteinlardan iborat, xromosoma faqat DNK",
        "Xromatin faqat hayvon hujayralarida, xromosoma - o‘simliklarda",
        "Xromatin DNKni parchalaydi, xromosoma sintezlaydi",
        "Xromatin ribosomada joylashadi, xromosoma mitoxondriyada",
      ],
      correct: 0,
    },
    {
      q: "Giston oqsillari qanday rol o‘ynaydi?",
      a: [
        "DNKni ixchamlashtirish va gen faolligini belgilash",
        "Protein modifikatsiyasini bajarish",
        "Lipidlarga signal uzatish",
        "Mikronaycha hosil qilish",
        "Hujayra bo‘linishini to‘xtatish",
      ],
      correct: 0,
    },
    {
      q: "Odam somatik hujayralaridagi xromosoma soni nechta?",
      a: ["46 ta (diploid 2n)", "23 ta (haploid)", "44 ta", "48 ta", "92 ta"],
      correct: 0,
    },
    {
      q: "Gomologik xromosomalar nima?",
      a: [
        "Bir xil shakl va genetik axborotni tashuvchi juft xromosomalar",
        "Mutatsiyaga uchragan xromosomalar",
        "Xromatinning faol shakli",
        "DNKni parchalaydigan organellalar",
        "Xromosoma ichidagi ribosomalar",
      ],
      correct: 0,
    },
    {
      q: "Aneuploidiya qaysi kasalliklarga olib keladi?",
      a: [
        "Daun sindromi, Klaynfelter sindromi, Turner sindromi",
        "Glikogen saqlash kasalligi",
        "MELAS",
        "Zellveger sindromi",
        "Chidiyak Higashi kasalligi",
      ],
      correct: 0,
    },
    {
      q: "Hujayralar signal uzatishda qaysi molekulalarni ishlatadi?",
      a: [
        "Ligandlar (gormon, mediator, oqsil yoki toksin)",
        "Faqat DNK molekulalari",
        "Faqat lipidlar",
        "Faqat mikronaychalar",
        "Faqat ribosomalar",
      ],
      correct: 0,
    },
    {
      q: "Autokrin signal uzatilishining xususiyati nima?",
      a: [
        "Hujayra o‘zi ishlab chiqargan ligand orqali o‘z retseptoriga ta’sir qiladi",
        "Hujayralar qon orqali uzoq masofaga signal yuboradi",
        "Faqat qo‘shni hujayralarga ta’sir qiladi",
        "Signal DNK ga kiradi",
        "Protein sintezini to‘xtatadi",
      ],
      correct: 0,
    },
    {
      q: "Parakrin signal uzatilishi qanday jarayonda sodir bo‘ladi?",
      a: [
        "Hujayralar qisqa masofada qo‘shni hujayralar bilan faoliyatini muvofiqlashtiradi",
        "Uzoq masofaga qon orqali signal uzatiladi",
        "O‘zi signalni o‘ziga yuboradi",
        "DNK o‘qiladi",
        "Ribosoma sintezini boshlaydi",
      ],
      correct: 0,
    },
    {
      q: "Endokrin signal uzatilishida qanday transport tizimi ishlatiladi?",
      a: [
        "Qon aylanish tizimi orqali uzoq masofaga ligand yetkaziladi",
        "Mikronaycha transporti",
        "Golji apparati orqali",
        "SET orqali",
        "Sitoskelet orqali",
      ],
      correct: 0,
    },
    {
      q: "Endokrin ligandlar odatda qaysi hujayralar tomonidan ishlab chiqariladi?",
      a: [
        "Ixtisoslashgan hujayralar: qalqonsimon, gipotalamus, gipofiz, jinsiy bezlar, oshqozon osti bezlari",
        "Ribosomalar",
        "Mikronaychalar",
        "Peroksisomalar",
        "Sitoskelet filamentlari",
      ],
      correct: 0,
    },
    {
      q: "Xromatin qanday fazada mavjud?",
      a: [
        "Hujayra o‘sish fazasida, bo‘linish amalga oshmayotgan paytda",
        "Mitoz paytida",
        "Meioz paytida",
        "Signal transduksiya vaqtida",
        "Protein modifikatsiyasida",
      ],
      correct: 0,
    },
    {
      q: "Xromosoma eukariot hujayralarda qanday shaklda bo‘ladi?",
      a: [
        "Chiziqli struktura, hujayra bo‘linishidan oldin kuchli spirallashgan",
        "Halqa shaklida",
        "Disk shaklida",
        "Tubalik shaklida",
        "Ixtiyoriy shaklda",
      ],
      correct: 0,
    },
    {
      q: "Ligand va retseptorning mosligi nima uchun muhim?",
      a: [
        "Signal uzatish faqat maxsus mos ligand-retseptor orqali sodir bo‘ladi",
        "DNK replikatsiyasi uchun",
        "Protein modifikatsiyasi uchun",
        "Lipidlarga transport uchun",
        "Mikronaycha hosil qilish uchun",
      ],
      correct: 0,
    },
    {
      q: "Yadro ichidagi suyuqlik qanday nomlanadi?",
      a: [
        "Nukleoplazma",
        "Sitoplazma",
        "Mitoxondrial matritsa",
        "Lizosomal matriks",
        "Golji bo‘shlig‘i",
      ],
      correct: 0,
    },
    {
      q: "DNKni erkin spirallashmagan holatda kim bilan bog‘langan?",
      a: [
        "Giston oqsillari bilan",
        "Mitoxondrial oqsillar bilan",
        "Ribosomal RNK bilan",
        "Peroksisomal ferment bilan",
        "Lipid molekulalar bilan",
      ],
      correct: 0,
    },
    {
      q: "Hujayralararo signal uzatilishning klinik ahamiyati nimada?",
      a: [
        "Organizmning biokimyoviy va fiziologik jarayonlarini muvofiqlashtirishda",
        "Protein sintezini to‘xtatishda",
        "Xromosoma sonini kamaytirishda",
        "Lipidlarga transportni oshirishda",
        "Mikronaychalarni hosil qilishda",
      ],
      correct: 0,
    },
    {
      q: "Ligand turi yo‘q bo‘lsa, nima sodir bo‘ladi?",
      a: [
        "Hujayralararo signal uzatilishi amalga oshmaydi",
        "Protein sintezi tezlashadi",
        "DNK degradatsiya qilinadi",
        "Mikronaychalar hosil bo‘ladi",
        "Golji apparati kengayadi",
      ],
      correct: 0,
    },
  ],
};
